# Dockerfile for the API Gateway Service
FROM node:lts-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./

COPY packages ./packages
COPY services ./services

RUN npm ci

RUN npm run build

RUN npm prune --production

FROM node:lts-alpine AS production
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/packages/ ./packages/
COPY --from=builder /app/services/api-gateway/ ./services/api-gateway/

EXPOSE 3000
CMD ["node", "services/api-gateway/dist/index.js"]